version: 2.1

aliases:
  - &working_directory ~/ctp-smoke-tests
  - &test_env_vars
    AUTH_URL: auth_url
    CLIENT_ID: client_id
    CLIENT_SECRET: client_secret
    PROJECT_KEY: project_key

executors:
  sbt-executor:
    docker:
      - image: openlaw/scala-builder
    working_directory: *working_directory
    environment:
      <<: *test_env_vars

jobs:
  compile:
    executor: sbt-executor
    steps:
      - checkout
       
      #git and sbt caching
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
            - sbt-cache
          
      - run:
          name: Compile smoke tests
          command: sbt -Dfatal-warnings=true -Dscalac-optimize=true clean test exit
       
      #git and sbt caching
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2.1
  build:
    jobs:
      - compile
