version: 2.1

aliases:
  - &working_directory ~/ctp-smoke-tests

  - &save-git-cache
    key: source-v1-{{ .Branch }}-{{ .Revision }}
    paths:
      - ".git"

  - &restore-git-cache
    keys:
      - source-v1-{{ .Branch }}-{{ .Revision }}
      - source-v1-{{ .Branch }}-
      - source-v1-

  - &save-sbt-cache
    key: sbt-cache
    paths:
      - "~/.sbt"
      - "~/.ivy2/cache"
      - "~/.m2"

  - &restore-sbt-cache
    keys:
      - sbt-cache

executors:
  sbt-executor:
    docker:
      - image: openlaw/scala-builder
    working_directory: *working_directory

jobs:
  smoke_tests:
    executor: sbt-executor
    steps:
      - checkout
      - restore_cache: *restore-git-cache
      - restore_cache: *restore-sbt-cache
      - run:
          name: Smoke tests
          command: sbt -Dfatal-warnings=true -Dscalac-optimize=true clean test exit
      - save_cache: *save-git-cache
      - save_cache: *save-sbt-cache

workflows:
  version: 2.1
  build:
    jobs:
      - smoke_tests

